### ISSUE TITLE
连续矩阵的逆运算

### ISSUE THREAD

**Issue by pearmini** [antvis/coord#25]
现在将连续的矩阵运算的逆运算合并成一个函数存在问题，导致在有连续的仿射变换的时候不能 invert 到原始值。

**Comment by hustcc** [comment]
自己给自己提 issue 也要描述一下，不然这个 issue 就没有什么意义了，直接本地用记事本做备忘也可以~

**Comment by pearmini** [comment]
> 自己给自己提 issue 也要描述一下，不然这个 issue 就没有什么意义了，直接本地用记事本做备忘也可以~
好滴
