### ISSUE TITLE
修改 Coordinate 设置默认 options 的方式

### ISSUE THREAD

**Issue by pearmini** [antvis/coord#28]
现在 Coordinate 设置默认 options 的方式是 constructor 里面赋值，更简洁的做法是在前面声明。

``` ts
class A {
  a = 1;
  constructor() {
    console.log('a');
  }
}
```

@hustcc  上面的 ts 代码编译成 js 如下: 

```js
"use strict";
class A {
  constructor() {
    this.a = 1;
    console.log('a');
  }
}
```

**Comment by hustcc** [comment]
如果有继承，有 super 的时候，编译出来应该是在 super 的后面

**Comment by pearmini** [comment]
> 如果有继承，有 super 的时候，编译出来应该是在 super 的后面

是的，之前在开发 scale 的时候就遇见过这个问题。
